### PR TITLE
Update version to 0.1.0

### PR DESCRIPTION
**Pull request by iph**
We are no longer on snapshot! Woo hoo!

### CODE REVIEW

**Comment by sanathkr** [comment]
It doesn't matter. Build tool will replace `version` property using ldflags on release. I would leave it as snapshot so local builds get a different version string.

**Comment by iph** [comment]
Ahh, missed that part since I kept getting the message being all "YOUR VERSION IS OUT OF DATE" from a `go install` perspective. Would it make sense to have TIP/HEAD not display that message for local development?

**Comment by iph** [comment]
talked with @sanathkr and we decided that snapshots should be ignored so that way local devs won't get annoyed by this :)

**Comment by sanathkr** [comment]
Closing this in favor of #23

**Pull request closed without merging**
