### PR TITLE
Use Inspector instead of Legacy Debugger

### PR DESCRIPTION
**Pull request by charsleysa**
Changes NodeJS 6.10 runtime debugging to use Inspector instead of Legacy Debugging.

A minor breaking change as debug tools need to have their config updated to use the Inspector protocol.

e.g. for VSCode inside launch.json you change `"protocol": "legacy",` to `"protocol": "inspector",`

### CODE REVIEW

**Comment by uipoet** [comment]
The legacy debugger in VSCode is useless as breakpoints are not working. Please merge this pull request as soon as possible.

**Comment by PaulMaddox** [comment]
Could you update the README to reflect this required change too? Once that's added i'm happy to merge this in and get it included in the next release. Thanks!

**Comment by singulli1** [comment]
FYI - this is an important fix for my team as well - we use the debugger extensively. It is currently broken.  Any movement on this would be greatly appreciated :).  Thanks so much.

**Comment by charsleysa** [comment]
@PaulMaddox updated README

**Comment by PaulMaddox** [comment]
Thanks @charsleysa!

**Comment by PaulMaddox** [comment]
There seems to be an issue with this PR - when i'm testing it, turning on debugging doesn't halt execution - it should automatically halt on the first line of code so you can attach the debugger.

I'll do some more testing later in the week to try and see what's up.

**Comment by singulli1** [comment]
Hello, were you able to resolve the issue with the PR?  is this item fixed  in the develop branch?
Thanks again for all your work.

**Comment by bradydowling** [comment]
I'm also having an issue with this PR/commit. It looks like `--inspect` does not report end of execution (in Node 6.10) so the debugger never knows when to disconnect. [This PR](https://github.com/nodejs/node/pull/12814) was made and merged for Node 7+ but never backported to Node 6.10.

Because of this, IDEs can't know when the debugger should detach. Is the note in the README suggesting that the user needs to manually detach the debugger upon program completion? This feels hackish.

@PaulMaddox is there a certain fix you implemented to get it to halt execution? Or was there a change you made in the IDE plugin?

**Comment by bradydowling** [comment]
I'm also curious, what caused the legacy debugger to break in VSCode? Was it working at some point and then it was broken by a change in SAM Local?

**Comment by singulli1** [comment]
FYI – After applying latest VSCode updates, the debugger (Legacy) is now working again with SAM local – I’m guessing changes to VSCode broke it, then they fixed it.

**Comment by bradydowling** [comment]
Ah that makes sense. Perhaps there should be an environment variable that allows you to override the run command altogether.

I added an environment variable to allow for [additional debugger args](https://github.com/awslabs/aws-sam-local/commit/453c34afa3c4fd380f59742771558a47ff2f0a3c) but replacing the command altogether may be preferable.

This could potentially future proof SAM Local from breaking changes or needs like this from other services or IDEs. If a certain IDE breaks or requires certain arguments, you can just pass that environment variable and override the whole run command.

**Pull request merged**
